influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
      #env_file:
      #- 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - /home/renyu/repo/deployment/docker-influxdb-grafana/influxdb:/var/lib/influxdb
      #- /home/renyu/repo/deployment/docker-influxdb-grafana/influxdb.conf:/etc/influxdb/influxdb.conf:ro

#telegraf:
#  image: telegraf:latest
#  container_name: telegraf
#  links:
#    - influxdb
#  volumes:
#    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
      #env_file:
      #- 'env.grafana'
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - /home/renyu/repo/deployment/docker/grafana/data:/var/lib/grafana
